name: Slack

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed

jobs:
  slack:
    if: github.event.workflow_run.conclusion == 'failure'
    runs-on: ubuntu-latest
    steps:
      - uses: miyajan/action-slack-workflow_run@v1.0.0
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
